# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipsvc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipsvc.proto',
  package='ipsvc',
  syntax='proto3',
  serialized_pb=_b('\n\x0bipsvc.proto\x12\x05ipsvc\"\x17\n\tIPRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"0\n\x07IPReply\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0b\n\x03loc\x18\x03 \x01(\t\"+\n\nIPsRequest\x12\x1d\n\x03ips\x18\x01 \x03(\x0b\x32\x10.ipsvc.IPRequest\"\'\n\x08IPsReply\x12\x1b\n\x03ipr\x18\x01 \x03(\x0b\x32\x0e.ipsvc.IPReply2h\n\x05IPSVC\x12-\n\x07IPQuery\x12\x10.ipsvc.IPRequest\x1a\x0e.ipsvc.IPReply\"\x00\x12\x30\n\x08IPSQuery\x12\x11.ipsvc.IPsRequest\x1a\x0f.ipsvc.IPsReply\"\x00\x62\x06proto3')
)




_IPREQUEST = _descriptor.Descriptor(
  name='IPRequest',
  full_name='ipsvc.IPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ipsvc.IPRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_IPREPLY = _descriptor.Descriptor(
  name='IPReply',
  full_name='ipsvc.IPReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ipsvc.IPReply.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='ipsvc.IPReply.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loc', full_name='ipsvc.IPReply.loc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=95,
)


_IPSREQUEST = _descriptor.Descriptor(
  name='IPsRequest',
  full_name='ipsvc.IPsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ips', full_name='ipsvc.IPsRequest.ips', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=140,
)


_IPSREPLY = _descriptor.Descriptor(
  name='IPsReply',
  full_name='ipsvc.IPsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipr', full_name='ipsvc.IPsReply.ipr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=181,
)

_IPSREQUEST.fields_by_name['ips'].message_type = _IPREQUEST
_IPSREPLY.fields_by_name['ipr'].message_type = _IPREPLY
DESCRIPTOR.message_types_by_name['IPRequest'] = _IPREQUEST
DESCRIPTOR.message_types_by_name['IPReply'] = _IPREPLY
DESCRIPTOR.message_types_by_name['IPsRequest'] = _IPSREQUEST
DESCRIPTOR.message_types_by_name['IPsReply'] = _IPSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IPRequest = _reflection.GeneratedProtocolMessageType('IPRequest', (_message.Message,), dict(
  DESCRIPTOR = _IPREQUEST,
  __module__ = 'ipsvc_pb2'
  # @@protoc_insertion_point(class_scope:ipsvc.IPRequest)
  ))
_sym_db.RegisterMessage(IPRequest)

IPReply = _reflection.GeneratedProtocolMessageType('IPReply', (_message.Message,), dict(
  DESCRIPTOR = _IPREPLY,
  __module__ = 'ipsvc_pb2'
  # @@protoc_insertion_point(class_scope:ipsvc.IPReply)
  ))
_sym_db.RegisterMessage(IPReply)

IPsRequest = _reflection.GeneratedProtocolMessageType('IPsRequest', (_message.Message,), dict(
  DESCRIPTOR = _IPSREQUEST,
  __module__ = 'ipsvc_pb2'
  # @@protoc_insertion_point(class_scope:ipsvc.IPsRequest)
  ))
_sym_db.RegisterMessage(IPsRequest)

IPsReply = _reflection.GeneratedProtocolMessageType('IPsReply', (_message.Message,), dict(
  DESCRIPTOR = _IPSREPLY,
  __module__ = 'ipsvc_pb2'
  # @@protoc_insertion_point(class_scope:ipsvc.IPsReply)
  ))
_sym_db.RegisterMessage(IPsReply)



_IPSVC = _descriptor.ServiceDescriptor(
  name='IPSVC',
  full_name='ipsvc.IPSVC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=183,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='IPQuery',
    full_name='ipsvc.IPSVC.IPQuery',
    index=0,
    containing_service=None,
    input_type=_IPREQUEST,
    output_type=_IPREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IPSQuery',
    full_name='ipsvc.IPSVC.IPSQuery',
    index=1,
    containing_service=None,
    input_type=_IPSREQUEST,
    output_type=_IPSREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IPSVC)

DESCRIPTOR.services_by_name['IPSVC'] = _IPSVC

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IPSVCStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.IPQuery = channel.unary_unary(
          '/ipsvc.IPSVC/IPQuery',
          request_serializer=IPRequest.SerializeToString,
          response_deserializer=IPReply.FromString,
          )
      self.IPSQuery = channel.unary_unary(
          '/ipsvc.IPSVC/IPSQuery',
          request_serializer=IPsRequest.SerializeToString,
          response_deserializer=IPsReply.FromString,
          )


  class IPSVCServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def IPQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def IPSQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IPSVCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'IPQuery': grpc.unary_unary_rpc_method_handler(
            servicer.IPQuery,
            request_deserializer=IPRequest.FromString,
            response_serializer=IPReply.SerializeToString,
        ),
        'IPSQuery': grpc.unary_unary_rpc_method_handler(
            servicer.IPSQuery,
            request_deserializer=IPsRequest.FromString,
            response_serializer=IPsReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ipsvc.IPSVC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIPSVCServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def IPQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def IPSQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIPSVCStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def IPQuery(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    IPQuery.future = None
    def IPSQuery(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    IPSQuery.future = None


  def beta_create_IPSVC_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('ipsvc.IPSVC', 'IPQuery'): IPRequest.FromString,
      ('ipsvc.IPSVC', 'IPSQuery'): IPsRequest.FromString,
    }
    response_serializers = {
      ('ipsvc.IPSVC', 'IPQuery'): IPReply.SerializeToString,
      ('ipsvc.IPSVC', 'IPSQuery'): IPsReply.SerializeToString,
    }
    method_implementations = {
      ('ipsvc.IPSVC', 'IPQuery'): face_utilities.unary_unary_inline(servicer.IPQuery),
      ('ipsvc.IPSVC', 'IPSQuery'): face_utilities.unary_unary_inline(servicer.IPSQuery),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IPSVC_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('ipsvc.IPSVC', 'IPQuery'): IPRequest.SerializeToString,
      ('ipsvc.IPSVC', 'IPSQuery'): IPsRequest.SerializeToString,
    }
    response_deserializers = {
      ('ipsvc.IPSVC', 'IPQuery'): IPReply.FromString,
      ('ipsvc.IPSVC', 'IPSQuery'): IPsReply.FromString,
    }
    cardinalities = {
      'IPQuery': cardinality.Cardinality.UNARY_UNARY,
      'IPSQuery': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'ipsvc.IPSVC', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
